name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main # Change this to your deployment branch if needed

jobs:
  apply_migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Try the operation up to 3 times
          for i in 1 2 3; do
            npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_PASSWORD }} && break
            echo "Attempt $i failed. Retrying..."
            sleep 5
          done

      - name: Update Supabase Config
        run: |
          npx supabase db update-config
          sleep 5 # Add small delay to ensure config is properly updated

      - name: Apply Supabase Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase db push || {
            echo "Migration failed. Checking logs..."
            npx supabase db reset
            exit 1
          }
